name: todo_app
description: "A full-featured task management application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.2.1
  desktop_notifications: ^0.6.3  # For desktop notifications
  timezone: ^0.10.0
  fl_chart: ^1.0.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  share_plus: ^11.0.0
  package_info_plus: ^8.3.0
  provider: ^6.1.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  app_settings: ^6.1.1 # For opening app settings
  home_widget: ^0.8.0
  permission_handler: ^12.0.0+1
  workmanager: ^0.6.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  crypto: ^3.0.6
  sqflite_sqlcipher: ^3.1.1
  file_picker: ^8.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.6
  build_runner: ^2.5.3
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true
